async function loadQuestions() {
  try {
    const res = await fetch("questions.json");
    if (!res.ok) throw new Error("File tidak ditemukan");
    const data = await res.json();
    return data;
  } catch (e) {
    console.warn("Gagal memuat soal default:", e);
    return []; // biarkan kosong tapi tetap jalan
  }
}
let defaultQuestions=[];let activeQuestions=[];const toastsEl=document.getElementById('toasts');function showToast(msg,type='info'){const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;el.style.marginTop='8px';el.style.padding='8px 12px';el.style.borderRadius='8px';el.style.background=type==='success'?'rgba(46,160,67,0.95)':(type==='warn'?'rgba(234,179,18,0.95)':'rgba(200,60,60,0.95)');el.style.color='#fff';el.style.boxShadow='0 6px 18px rgba(0,0,0,0.12)';toastsEl.appendChild(el);setTimeout(()=>el.remove(),3200);}async function loadDefaultQuestions(){try{const res=await fetch('questions.json');defaultQuestions=await res.json();activeQuestions=defaultQuestions.slice();}catch(e){defaultQuestions=[];activeQuestions=[];}}document.getElementById('uploadBtn').addEventListener('click',()=>document.getElementById('fileInput').click());document.getElementById('uploadBtn2').addEventListener('click',()=>document.getElementById('fileInput').click());document.getElementById('fileInput').addEventListener('change',(ev)=>{const f=ev.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=(e)=>{try{const data=XLSX.read(e.target.result,{type:'binary'});const sheet=data.Sheets[data.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(sheet,{header:1});const parsed=[];for(let r of rows){const q=(r[0]||'').toString().trim();const a=(r[1]||'').toString().trim();const b=(r[2]||'').toString().trim();const c=(r[3]||'').toString().trim();const key=(r[4]||'').toString().trim().toUpperCase();const tfq=(r[5]||'').toString().trim();const tfk=(r[6]||'').toString().trim().toLowerCase();if(q){parsed.push({type:'pilihan',question:q,options:[a,b,c],answerIndex:key==='B'?1:(key==='C'?2:0)});}if(tfq){parsed.push({type:'benar_salah',question:tfq,answer:(['benar','b','true','ya','1'].includes(tfk))});}}if(parsed.length>0){activeQuestions=parsed;showToast('✅ Soal berhasil dimuat! Soal bawaan dinonaktifkan.','success');}else{showToast('⚠️ Format file tidak sesuai atau kosong.','warn');}}catch(err){console.error(err);showToast('❌ Gagal memuat soal.','error');}};reader.readAsBinaryString(f);});document.getElementById('settingsBtn').addEventListener('click',()=>document.getElementById('settingsMenu').classList.toggle('hidden'));document.getElementById('closeSettings').addEventListener('click',()=>document.getElementById('settingsMenu').classList.add('hidden'));document.getElementById('aboutBtn').addEventListener('click',()=>alert('Ular Tangga Edukatif - by Apipudin, SDN NAGREG 05'));window.addEventListener('DOMContentLoaded',async()=>{await loadDefaultQuestions();document.getElementById('loaderOverlay').classList.add('hidden');document.getElementById('splash').classList.remove('hidden');});
